version: '3'
services:
  node:
    build:
      context: ./server/budgi_backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: node
    volumes:
       - ./server/budgi_backend:/usr/src/app/server/budgi_backend
       - /usr/src/app/server/budgi_backend/node_modules
  angular:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: angular
    volumes:
       - ./website:/usr/src/app/website
       - /usr/src/app/website/node_modules